DDMAL/Neon

- src/Select.js
Fixes #134 it seems. Refactors triggerNcActions to not require a
`lastSelect` array. Reflects that in Select.js. Also adds support for
changing head shape on drag selecting a single neume component, which we
apparently didn't have before.
> Fix issues with passing selection to nc action

- src/Text.js
Display syllables without text as a &#x25CA; instead of a blank
rectangle. Also show an alert the first time one will be rendered to
explain what the symbol means in this context. #157.
> Improve syllable UI, add info message on edit mode

- src/Compatibility.js
- src/NeonView.js
Resolve #174.
We were passing the entire file path to revert, so it wasn't even being called on the server since the file path didn't match the pattern. This now works and when the POST request is successful, Neon will automatically refresh the page, loading the reverted page.
> Fix revert in standalone mode.

- src/DragHandler.js
- src/Select.js
With all the contextual selection (ie selecting a syllable as a neume if
it's one neume) make sure to check that the syllable wasn't already part
of a selection. Keeps from interfering with drag selections and dragging
these selections.
Resolve #207.
> Don't reselect on click if element already selected

- src/Color.js
- src/Select.js
Run the updateHighlight function when selecting a new element. Also when
updating a highlight by grouping ensure a parent in the DOM hierarchy is
not marked as selected. If so don't apply the highlight (since it will
override the selection fill on a higher up element).
Resolve #220.
> Run highlight on selection and don't override select fill

- src/InsertHandler.js
Previously clickaway happened when the user clicked on a `path` element
that forms a staff line. Now it shouldn't disable insert mode without it
being a click outside of the entire svg container.
Resolve #240.
> Prevent insert clickaway on other SVG elements.

- src/Controls.js
- src/NeonView.js
Previously was available on load in NeonView, making it available before
entering edit mode and sometimes adding multiple listeners to it.
Resolve #243.
> Move save hotkey to navbar init so it's called once.

- src/Notification.js
Mode messages are defined as any message containing the substring
"Mode". This means an "Edit Mode" notification is dismissed if an
"Insert Mode" notification is to be displayed, or vice versa.
Resolves #244.
> Automatically dismiss mode messages if another is queued.

- src/Select.js
Don't give the option to group when the selection is already grouped.
Also give the next-highest grouping option if the selection makes up
that entire higher-level group. For example if selecting by NCs and an
entire neume is selected, give the neume option. If selecting by NCs and
part of a neume is selected (but all the NCs are in the same neume),
give no options.
Resolves #251.
> Refine when we show grouping options.

- src/Notification.js
- src/style.css
- views/editor.pug
Move notifications out of navbar. Behaviour otherwise the same.
Floating notification with half opacity background
Resolve #286.
This will require changes in [the wrapper](https://github.com/DDMAL/neon2-wrapper).
> Overlay notifications on canvas.

- src/Select.js
Call `dragHandler.dragInit` on every new select action. Do not click
reselect on a part of an existing selection (since this is probably
dragging a drag selection, not making a new selection). Fix an issue
where we called a jquery method on an `HTMLElement`.
Check manually before merging into develop for correctness. It looked
good on my end but I might've missed something. Context options from `selectAll` seem right.
Also I found a `LogMessage` in `src/editortoolkit.cpp` under `EditorToolkit::Remove`. We don't need to rebuild it now but next time we make a change to verovio we should ensure that message isn't being sent every time `Remove` is called.
> Fix select/drag issues from refactor/select merge.

- src/Controls.js
Resolve #298. Use `addEventListener` so we can access `KeyboardEvent.code` since that is not copied in the jQuery event object.
> Bind hotkey to Shift+num for insert options.

- src/InsertHandler.js
Button added in the edit panel when insert mode is entered, and
disappears when insert mode is exited. Clicking the button exits insert
mode.
If this doesn't seem like the best solution to #307 we can change it with another commit and then squash and merge once everything is ready.
> Add a "Return to Edit Mode" button in insert mode.

- src/DragHandler.js
- src/Select.js
Now dragging a staff and its elements can be done by clicking anywhere
within the staff and not just on the actual SVG elements. This was done
by sending a `mousedown` action to the staff SVG when click selecting
off the SVG and, in that case, temporarily setting the dragging actions
to use `#svg_group` as a source for `mousemove` and `mouseup` actions.
Resolve #296.
> Support dragging staves from any part of staff

- src/DragHandler.js
- src/Grouping.js
- src/InsertHandler.js
- src/Select.js
- src/SelectOptions.js
Fixes issues #308 and #314.
When the user makes a call to set two neume components to become a ligature, now first both neume components have the virga and inclinatum parameters automatically unset. This allows them to render correctly and ensures the MEI makes sense, but toggling the ligature off does not restore these parameters.
Ensure the event listeners on `svg_group` are restored at the end of a drag action called from `DragHandler`. It was originally replaced and removed to get more intuitive on click staff dragging, but this required putting a listener for staff dragging on `svg_group`, which replaced the drag select listeners.
> Fix toggling ligatures with non-punctums, fix drag select

- package.json
- setup-verovio
- verovio-util/verovio-js-start.js
- verovio-util/verovio-npm-end.js
- verovio-util/verovio-npm-start.js
- verovio-util/verovio-proxy.js
- views/editor.pug
- webpack.config.js
- webpack.pages-config.js
Rather than putting the verovio module into a single Neon2 editor.js
file, we distribute it separately and use webpack to handle loading.
Tests still pass and the NPM module is still available.
The same is done for jquery and d3 since they are likely to be cached.
> External verovio to avoid webpack issues

- src/utils/Select.js
Check to see if navigator.oscpu contains "Mac". If it does, check for
cmd being pressed. Otherwise use ctrl. Resolves #381.
> multi-select with cmd-click on mac

- src/SquareEdit/Contents.js
- src/SquareEdit/Grouping.js
- src/utils/SelectTools.js
- test/NeonView.test.js
- test/resources/test.mei
This adds support for selecting syllables across staves. If two syllables are selected that *could* be split by a staff break, the option is given to link them. If two syllables are linked, selecting one automatically selects the other as well.
This resolves #306.
> Support for selecting syllables across staves

- .travis.yml
- package.json
- src/NeonCore.js
- src/NeonView.js
- src/VerovioWorker.js
- src/VerovioWrapper.js
- src/utils/EditControls.js
- test/NeonCore.test.js
- test/SinglePageBrowser.test.js
- test/VerovioWrapper.js
Move verovio into a web worker. `src/VerovioWorker.js` is the worker itself. `src/VerovioWrapper.js` exists as a buffer so we can cleanly mock this entire part for testing in jest.
Resolve #346.
> Put Verovio into a web worker

- src/utils/Select.js
Require selection mode to not be bbox in order to select anything with a use tag (including custos and clefs). Resolves #417
> prevent selection of neume elements while in selectByBBox mode

- src/NeonView.js
- test/DivaBrowser.test.js
- test/test/diva-test/manifest.jsonld
- test/test/diva-test/output_split_salzinnes_014.mei
- test/test/diva-test/output_split_salzinnes_522.mei
Begin adding tests against Neon using diva.js as a viewer. Since most features are shared between the single page view and diva.js view, fewer tests are needed for this mode. Tests are run on Firefox, Chrome, and Safari.
Resolves #405.
> Add tests for Neon using diva.js

- src/utils/Select.js
Resolve #455. This just checks if an element is a half of a ligature using the glyph, then looks for the element before or after it depending on which half of the ligature it is. It then ensures that neighboring element will be part of the selection.
> Select entire ligature on drag select.

- src/utils/NeonManifest.js
This is an improved way of verifying that the `@context` entry of a loaded manifest file is what is expected by Neon. Previously string comparison was used assuming that if objects had value equality that `JSON.stringify` would always output them in the same order. This is not the case. This also addresses DDMAL/neon-wrapper#18.
> Check against values of @context object

- package.json
- src/NeonCore.js
- src/utils/ConvertMei.js
- src/utils/EditControls.js
- test/ConvertMei.test.js
- test/__mocks__/uuid/v4.js
- test/resources/testSb.mei
- test/resources/testStaff.mei
- yarn.lock
Functionality is added to convert back and forth between `<staff>`- and `<sb>`-based MEI files within Neon. Files can be loaded regardless of mode and when downloading a single MEI file via the toolbar, the file is in `<sb>`-based mode.
Resolve #347
> Handle staff and sb based MEI files in Neon

- pages/editor.js
- pages/static/index.html
- pages/static/storage.js
- src/utils/random.ts
- tsconfig.json
Permits a user to select an MEI file and background image (JPEG or PNG) and generates a manifest with these files encoded as data URIs. UUIDs are generated using functions written in `src/utils/random.ts` that are compiled to JavaScript and added to `storage.js`. These functions work and generate valid version 4 UUIDs.
ES2017 is used as a target to give access to `String.prototype.padStart`. The [Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Crypto) is used to generate the random values used in the UUIDs.
Resolves #532.
> Allow upload of single single pages on GH pages without a manifest

- src/NeonView.ts
- src/SquareEdit/InsertHandler.ts
- src/SquareEdit/SelectOptions.ts
- src/SquareEdit/StaffTools.ts
- src/utils/Resize.ts
- src/utils/Select.ts
- test/SinglePageBrowser.test.ts
resolve #581
resolves #588 
resolves #591 
also removes updateForCurrentPagePromise() and all references to it
for the multiple deselecting there are two options:
```
const temp = document.querySelector('.sel-by.is-active').id;
let mode = '';
switch (temp) {
case 'selByStaff':
mode = '.staff';
break;
case 'selByNeume':
mode = '.neume';
break;
case 'selByNc':
mode = '.nc';
break;
default:
mode = '.syllable'
break;
}
let remove = [this.closest(mode)];
```
or 
```
let remove = [this.closest('.syllable'), this.closest('.neume'), this.closest('.nc'), this.closest('.staff')];
```
both will need to be updated if and when any new types of elements are added. the first one seems somehow better, and probably is slightly better computationaly (see the .filter call just after), but the second is much …
> visual feedback for split

- src/DisplayPanel/DisplayControls.ts
- src/SquareEdit/Controls.ts
This makes it so the user only needs to click on the actual SVG where
the triangle is rather than only on the triangle.
Fix #585.
> Apply event listener to SVG element instead of G

- test/SinglePageBrowser.test.ts
- yarn.lock
Update @typescript-eslint/eslint-plugin to 2.16.0
Update typedoc to 0.15.8
Update webpack to 4.41.5
Safari tests in SinglePageBrowser are also temporarily removed.
> Update vulnerable dependencieas

- deployment/server/editor.ts
- src/SingleView/SingleView.ts
Neon needs the bounds of the source to create the `viewBox` for the SVG containing (in single page mode) the background image and rendered MEI. This allows gets a tentative BBox from the background image itself and uses that to set the `viewBox`, which should make the page appear normally before the MEI loads (or if the MEI is not formatted correctly).
Also the viewer mode to load in is determined by the number of annotations in the manifest file, not by loading the content of `manifest.image` and seeing if it is a IIIF manifest or an actual (large) image file.
> Get viewBox from background image

- deployment/views/editor.pug
- src/SquareEdit/Grouping.ts
- src/utils/ConvertMei.ts
- src/utils/SelectTools.ts
- test/SinglePageBrowser.test.ts
- test/resources/test.mei
- yarn.lock
Vaules of `@facs` (and `@follows` and `@precedes`) should actually be URIs as pointed out in #603 . This involves some fixes to automate using a fragment (e.g. `#someId`) in these cases to link to another element in the same document.
> Made `@facs` value a URI fragment

- src/utils/ConvertMei.ts
See the commit message for more details, but basically a `custos` being allowed in `sb` was a mistake.
> Write custos outside of sb

- package.json
- test/__mocks__/pouchdb.js
- yarn.lock
Fix #614. Changing the order of preferred adapters does in fact change the order in which they're tried. `pouchdb-core` is used since `pouchdb` is too large to load with jest right now.
> Switch to memory adapter

- src/NeonCore.ts
- src/NeonView.ts
Specifically just delete the documents for the manifest and annotations
in that manifest and NOT the entire database for Neon.
Resolve #621.
> Only delete documents used in NeonCore

- src/utils/SelectTools.ts
I added `console.log()` statements to all functions that called the `changeStaffHandler` and the issue seemed to be `groupsToSelect` not calling the necessary functions to trigger the button. I've added it to all three sections with possible syllable calls but it may not be needed in all of them.
> Fixed #681 by adding syl action triggers to groups

- .eslintrc.json
- src/DisplayPanel/DisplayControls.ts
- src/InfoModule.ts
- src/SquareEdit/Contents.ts
- src/SquareEdit/Controls.ts
- src/SquareEdit/Grouping.ts
- src/SquareEdit/InsertHandler.ts
- src/SquareEdit/NeumeTools.ts
- src/SquareEdit/SelectOptions.ts
- src/SquareEdit/StaffTools.ts
- src/TextEditMode.ts
- src/Warnings.ts
- src/utils/Color.ts
- src/utils/ConvertMei.ts
- src/utils/DragHandler.ts
- src/utils/EditControls.ts
- src/utils/NeonManifest.ts
- src/utils/Notification.ts
- src/utils/Resize.ts
- src/utils/Select.ts
- src/utils/SelectTools.ts
- src/workers/VerovioWorker.js
- tsconfig.json
Fix files according to ESlint rules.
Changes to ESlint:
- Remove `no-use-before-define` rule.
- Add `object-curly-spacing` and `quote-props` so that our code looks prettier. 😃
Comments:
- A lot of typing needs to be fixed.
- ESlint still does not stop from long lines of code that go pass the standard 80 characters per line. Also, ESlint does not auto format such long lines. I'd suggest we use Prettier as an extension to ESlint. I've used Prettier extensively and it autoformats not just long lines of code but also long function signatures and long imports.
> Fix files according to ESlint rules

- src/Types.ts
- src/utils/Select.ts
- src/utils/SelectTools.ts
Adds feature requested by @carrieeex in issue #665 to use arrow keys for moving between bounding boxes.
> It would be nice if we can use arrow keys (left and right) to switch between different bounding boxes. For example, when users choose "select by BBox", and then click one of the bounding boxes, press the right arrow key would switch to the BBox on the right.
Demo:
https://user-images.githubusercontent.com/40512164/167648259-9f4c0e5c-f1fe-4d19-9104-40f55601e24b.mov
EDIT:
Arrow keys now move correctly through syllables.
https://user-images.githubusercontent.com/40512164/167668314-40c98e51-917e-4510-a7ad-e85330b46b73.mov
> Add arrow key shortcuts.

- src/utils/SelectTools.ts
#797
Fix toggle ligature option not appearing for cmd+selecting nc's that could be converted to a ligature. 
**Note: podatus still shows the option to toggle ligature - tldr podatus and ligature presented as an svg is identical. But, toggle ligature on a podatus will not functionally change anything. Optimal fix coming soon!**
> fix cmd-select nc's for toggle ligature

- src/utils/Color.ts
- src/utils/SelectTools.ts
Divlines now appear red when selected by user. Previously, there was no visual indication that a divline had been selected, which led to occasional confusion (especially in cases when divlines were selected by mistake).
> Selected Divline Fix

- src/utils/EditControls.ts
Fixes #820 
Changed neume.remove() and syllable.remove() to actual neonView edit actions. This change allows the svg on the page to be updated immediately after the action occurs. Additionally, it is now possible to undo and redo the action of removing empty neumes and syllables.
> Empty Neume/Syllable removal now immediately updates the page.

- src/NeonCore.ts
- src/NeonView.ts
- src/SquareEdit/Grouping.ts
- src/SquareEdit/InsertHandler.ts
- src/SquareEdit/NeumeTools.ts
- src/SquareEdit/SelectOptions.ts
- src/SquareEdit/StaffTools.ts
- src/TextEditMode.ts
- src/Types.ts
- src/utils/DragHandler.ts
- src/utils/EditControls.ts
- src/utils/Resize.ts
- test/NeonCore.test.ts
Fixes #807 .
Most significantly, editor actions have been given a full makeover with exact types.
> 🏷 Add correct TypeScript types throughout the project

- src/SingleView/Zoom.ts
Fixes #683 .
Undo accidental change in resetZoomAndPan() function in `Zoom.ts`. I looked at `git log -p -- src/SingleView/Zoom.ts` and this seems to be the culprit. Everything else works as before.
https://user-images.githubusercontent.com/40512164/170086205-36b88049-0853-4ce5-bad4-e7ed48f58a2d.mov
> 🐛 Fix reset zoom button.

- src/DisplayPanel/DisplayControls.ts
- src/SquareEdit/Contents.ts
deactivates default action on up and down arrow for slider, change shortcuts to _ and +.
Fixes #850
> fix zoom shortcuts and up/down arrow reactivity🐛

- src/NeonCore.ts
- src/NeonView.ts
- src/SingleView/SingleView.ts
Fixes #767 .
Dereferences SVG object when `NeonCore.edit()` is called.
In my personal usage, what used to take up to 16 GB of RAM on my computer now takes up only 300 MB of RAM.
Memory usage in Neon should now be consistent (except due to the storing of strings in undo/redo stacks).
Google Chrome, Safari, and Microsoft Edge.
EDIT: Works on Firefox as well.
Storing of strings must be fixed in the future.
The MEI string and SVG object of neonCache should be accessed through a memory-safe function.
> 🚑 Fix severe memory leak (high memory consumption)

- src/utils/ModalWindow.ts
Fixes #869 
Edit-Text modal windows should now always display the correct syllable and behave properly.
> 🐛 Fixes modal window bug that caused Edit-Text modal windows to display the wrong text.

- assets/style.css
- src/DisplayPanel/DisplayControls.ts
- src/DisplayPanel/DisplayPanel.ts
- src/InfoModule.ts
- src/SquareEdit/Contents.ts
- src/SquareEdit/Controls.ts
- src/SquareEdit/DivaEditMode.ts
- src/SquareEdit/InsertHandler.ts
- src/SquareEdit/SingleEditMode.ts
- src/TextView.ts
I also slightly modified the functionality from how it used to be in Neon. Now, if a user is in Insert mode and clicks away, they are taken to Edit mode only if they click on the Edit panel. In all other situations, the user will be kept in the mode that they were in prior to clicking anywhere on the page.
Also, instead of highlighting the panel, I thought it was more elegant to simply underline the panel title. This can be easily changed if it is decided that highlighting the panel is preferred.
> ✨ 💄 Added visual cues that tell users if they're in Edit mode or in Insert mode.

- src/SquareEdit/Contents.ts
- src/SquareEdit/SelectOptions.ts
- src/utils/SelectTools.ts
Fixes #879 and issue from #862 by refactoring SelectOptions.ts, replacing empty try/catches for explicit null checks or optional chaining.
- Use one setEditControls() function to set moreEdit and extraEdit content, so that we do not use empty try/catch's and have to only call ONE function.
- Add addDeleteListener() and addChangeStaffListener() which do null checks instead of try/catch. Replace all try/catches with addDeleteListener() or addChangeStaffListener().
- Add optional chaining for insertToSyllable and moveOuttaSyllable.
- TODO: any event listeners should be removed before a new one is created. Example: insertToSyllable and moveOuttaSyllable addEventListeners.
> ♻️🐛 Replace try/catch for explicit null checks.

- src/utils/Select.ts
Fixes #871 .
Refactors clickHandler() in Select.ts .
> 🐛♻️ Fix selection of multiple staves by cmd-click

- src/SquareEdit/InsertHandler.ts
- src/SquareEdit/StaffTools.ts
- src/Types.ts
- src/utils/Coordinates.ts
- src/utils/DragHandler.ts
- src/utils/Select.ts
Fixes #895 by adding a new file called Coordinates.ts with a revamped calculation of SVG-relative coordinates. In my testing, getSVGRelCoords() gives the identical coordinates to what was being calculated before.
Also,
- There are still SVGPoint code in Zoom.ts and Select.ts, which require different calculation than getSVGRelCoords().
- For both getSVGRelCoords() and getStaffIdByCoords(), there is commented out code for an alternative calculation in case that is needed in the future.
> ♻️➖ Remove SVGPoint (deprecated) for getSVGRelCoords()

- src/utils/ConvertMei.ts
Fixes #886 .
Previously, we were finding the next syllable with positional indices (hence, n+1th syllable should be the following syllable for the nth syllable), which doesn't work when there are syllables in between the toggle-linked syllables.
The solution is to find the syllable in the array by the ID instead, which handles this edge case.
The time complexity stays the same, linear time.
> 🐛 Fix @follows/@precedes check with Array.find()

- src/utils/Select.ts
- src/utils/SelectTools.ts
Improve performance of drag selection when group highlights are enabled. Drag selecting even a small portion of the folio with group highlights on would freeze Neon for a good second or more. With this fix, time taken is reduced by 99%!
Before:
https://user-images.githubusercontent.com/40512164/178828738-0dffc35b-1209-407d-b25c-ac382de92913.mov
After:
https://user-images.githubusercontent.com/40512164/178828743-0b776594-1ca3-403e-b9f8-1c3e3c120b17.mov
> ⚡️ Improve drag selection performance

- assets/style.css
- src/SquareEdit/Grouping.ts
- src/SquareEdit/InsertHandler.ts
- src/SquareEdit/NeumeTools.ts
- src/SquareEdit/SelectOptions.ts
- src/SquareEdit/StaffTools.ts
- src/utils/ConvertMei.ts
- src/utils/DragHandler.ts
- src/utils/EditControls.ts
- src/utils/Notification.ts
- Add 'default', 'error', 'warning', 'success' types
- Set opacity to 1 for notifications
- Add emojis for notifications :)
- Changed a couple notifications to have these new types, not all of them though
> ✨ Add types to notifications

- src/utils/Coordinates.ts
Previous calculation would make all dragging false positives.
> 🚑 Fix OOB calculation for <rect>

- src/utils/DragHandler.ts
Related to #700 ... I made a mistake again when I included <rect>s into OOB calculation, since <rect>s all have x=0,y=0 coordinates when bounding boxes are not displayed. This PR fixes it
> 🚑 Exclude <rect> from OOB check if bboxes are hidden

- src/Dashboard/DocumentSelector.ts
- Users can now open folios quickly simply by double-clicking on a file name.
- This is instead of having to select (click) a document, and then clicking the "open docs" button
> ✨ Feature that allows users to quick-open documents by double-clicking

- src/TextEditMode.ts
- src/utils/ModalWindow.ts
There was an error with updateSelectedBBox() which would be called any time the user edits the syl text of a bounding box. This issue seemed to have been due to some misorganization and perhaps discarded during a hasty merge of a pull request.
Anyways, it has been extracted into its own method which can be called from both TextEditMode.ts and ModalWindow.ts
> 🐛 Fix non-existent updateSelectedBBox()

- cypress/e2e/displace.cy.ts
- cypress/e2e/dropdown.cy.ts
- src/SquareEdit/Contents.ts
- src/SquareEdit/SelectOptions.ts
- src/Types.ts
- src/utils/Notification.ts
Fixes #648 .
https://user-images.githubusercontent.com/40512164/184015868-62a1abaa-064b-47dd-b8dd-622a0237d8f1.mov
Before this PR can be merged, there's one issue:
@annamorphism or @JoyfulGen , what is the minimum / maximum octave a neume can be? Currently, clef displacement has free reign and can lead to neumes having a -1 octave. From my testing, the maximum octave a neume can be is 6.
> ✨ Add octave displacement for clefs

- src/utils/SelectTools.ts
Fixes #966 
Users are now able to group neumes that appear to be adjacent visually, but may not be represented that way in the MEI file.
> ✨ Re-introduce feature that allows grouping of certain non-adjacent neumes.
