DDMAL/Neon

public/src/DragController.js
Resolves issue #2 (moving clefs).
=> Feature moving clefs

public/src/DragController.js
Main changes are made to verovio, reuses same drag listeners as for NCs.
Changes to verovio in branch [feature-implement-custos](https://github.com/ATranimal/verovio/tree/feature-implement-custos).
=> Implement custos display & movement

views/editor.pug
Added help button the redirects to the Neon Wiki.
=> Added help button

src/InsertHandler.js
=> Stay in insert mode until user pushes "Escape".

src/NeonView.js, src/ViewControls.js
=> Reapply staff highlight and show/hide syl when MEI refreshed

src/EditMode.js
Resolves #99 and uses the chain action in Verovio
=> Add delete button to remove selected elements

src/DragSelect.js
=> No duplicate selected classes

src/EditMode.js, src/Select.js, test/Neon.test.js
Use `vrv::EditorToolkit::Set` to change head shape for punctums. Can set to regular, inclinatum, or virga. Also test of Set function is present in `test/Neon.test.js`.
Also storing the selected ncs in an array in `src/Select.js` since they are deselected before the action can be completed and we need the ID for Verovio.
=> Implement change head shape

src/Color.js, src/Controls.js, src/NeonView.js, views/editor.pug, yarn.lock
Use bulma dropdown. Last selection saved using a class added to the
option in the menu (except none). Also update verovio to develop.
=> Allow highlighting by staff, syllable, neume.

src/Controls.js, src/Select.js, views/editor.pug
Fixed select listeners to clear selection when changed. Also added the dropdown icon to the Highlight menu.
=> fixed select listeners and and dropdown icon

src/InsertHandler.js
Should prevent multiple insert actions at once and resolve #137.
=> Add only one click listener for inserting maximum.

src/Contents.js, src/InsertHandler.js
Green dot appears on first click for insert. Will also decide which
point is ul and which is lr automatically and not rely on user clicking
in order. Resolve #136.
=> Feedback and checking added to staff insert.

src/Controls.js, src/EditMode.js, src/Text.js
For the issue with clicking on text to edit it not working when the display text box was not checked when switching to edit mode.
=> Fix setting listener for editing text. Fix #145.

src/Contents.js, src/Grouping.js, src/Select.js, src/SelectOptions.js
Not the smartest but it gets the job done for now. Should be refined w
user feedback. Resolve #84
=> Allow toggling ligature when 2 ncs selected

src/Contents.js
=> Remove quilisma and white punctum from insert

src/Controls.js, src/EditMode.js
Stops the two prompt problem. Resolves #152
=> Prevent two listeners from being put on syl text.

src/InsertHandler.js, src/Select.js
=> Support panning in insert mode when shift pressed

src/Text.js
=> Properly handle setting syllable text to blank.

src/Select.js
=> Support click/drag selecting any part of staff

src/EditMode.js, src/Select.js
currently can't drag the staff immediately right now if it's not the SVG clicked on. #198.
=> Real click select for staves

server/routes/index.js, src/editor.js
=> Remove an autosave if the user does not load it.

src/Select.js
=> Don't allow click select/drag in insert mode.

src/NeonView.js, src/style.css, views/editor.pug
Dismissed when the background image is fully loaded since this is the
main bottleneck. Resolves #235.
=> Add loading animation for Neon2.

src/Color.js, src/Select.js
Fix select fill of staff when highlighting by syl/neume
Prevent highlight on staff from disappearing when going from staff highlight to no highlight
Resolves #249.
=> Handle conflicting highlight and select on same elements.

src/style.css
=> Adjust padding on notifications.

src/Select.js, src/Text.js
If any neume components in a syllable are highlighted and the text is
displayed, the text will also be highlighted. Resolves #245.
=> Reverse highlighting of syllables.

src/Select.js
Similar logic to what's done with drag select. Resolves #256
=> Disable click select when panning

src/Compatibility.js
Copies the same action as autosave, since there is no distinction in the
Rodan version. Resolves DDMAL/neon2-wrapper#12.
=> Add file save action in Rodan.

src/Select.js
Check if the rectangle contains any point in the glyph rather than just
the upper left corner. Resolves #262.
=> Check drag select by any point in the glyph

src/Color.js, src/Select.js
ligature selection based on new selection box.
=> added check for ligature

src/Color.js, src/Compatibility.js, src/Contents.js, src/Controls.js, src/Cursor.js, src/DragHandler.js, src/EditMode.js, src/Grouping.js, src/InfoBox.js, src/InsertHandler.js, src/NeonView.js, src/Notification.js, src/ResizeStaff.js, src/Select.js, src/SelectOptions.js, src/SplitHandler.js, src/Text.js, src/Warnings.js, src/Zoom.js, src/editor.js, test/Notification.test.js, webpack.config.js, webpack.pages-config.js
Add test for `Notification.js`. Have JQuery and d3 specifically included in files where they're used instead of available as plugins so we're able to use them in tests that require them.
Also ran a linter to make code more standardized and fixed an issue with our document annotations that pointed to `NeonView` instead of `Neon`.
=> Refactor for tests, some cleaning

src/style.css
=> Modify CSS so SVG + BG fill the output field

src/Grouping.js, src/Select.js, webpack.config.js
Uses DDMAL/verovio@bddd6f1. Had to rework merging syllables since as is
it would also give IDs for the SYL tag.
=> Update to Verovio with new Group

src/EditMode.js, src/InsertHandler.js
Got rid of corner notifications, changed color of panel headers and bolded header text. Resolves #335.
=> Change notifications for edit/insert mode

test/NeonView.test.js, yarn.lock
Improve tests for NeonView as mentioned in #349.
=> Improve NeonView tests

server/routes/index.js, views/index.pug
Restricts to PNG file type as well since that's what we officially
support. Resolves #353.
=> Use multer.memoryStorage for uploading files.

src/NeonCore.js
This uses an updated version of Verovio with setting/unsetting the `@ligated` attribute fixed. Since this is from the PR branch, it adds the `useFacsimile` option to maintain our layout.
Resolves #369.
=> Fix toggling ligatures

src/SquareEdit/Contents.js, src/SquareEdit/SelectOptions.js, src/utils/Select.js, src/utils/SelectTools.js
Last commit to finish up the PR for #343. Also handles #377.
=> Rewrite selectAll, add delete button for any selection.

src/utils/Select.js
=> Start drag init after click-select.

package.json, pages/editor.js, pages/static/editor.html, pages/static/index.html, pages/static/storage.js
=> Update GH pages editor, generate complete dist/

.travis.yml, test/SinglePageBrowser.test.js
Required rewriting some tests to avoid crashes in Safari (for some unknown reason) and also enabling safaridriver in travis.
=> Run browser tests in Safari

src/SquareEdit/Contents.js, src/SquareEdit/Controls.js, src/SquareEdit/DivaEditMode.js, src/SquareEdit/InsertHandler.js, src/SquareEdit/SingleEditMode.js
Implement features described in #422.
=> Update insert panel

src/SquareEdit/DivaEditMode.js, src/SquareEdit/SingleEditMode.js, src/TextEditMode.js, src/TextView.js, src/style.css, src/utils/Color.js, src/utils/DragHandler.js, src/utils/Resize.js, src/utils/Select.js, src/utils/SelectTools.js
refactor bounding box selecting so that the 'selected' class is added to the syl parent. resolves #427 #411
=> refactor bbox selecting and fix bug

pages/static/editor.html, src/DivaView.js, src/NeonCore.js, src/utils/EditControls.js
DivaView will not load a page unless it is active (as defined by diva.js) for 500 ms. Plus minor bug fixes.
Resolve #437  and #418.
=> Add timer to loading MEI file

src/NeonCore.js, test/DivaBrowser.test.js, test/NeonCore.test.js, test/SinglePageBrowser.test.js
=> write tests for text editing module

src/InfoModule.js, test/SinglePageBrowser.test.js
This pr is just to run the travis tests and to make the changes done very visible
=> 428 InfoModule behaviour

src/SquareEdit/Grouping.js, src/TextView.js
When two syllables are linked as being split across staves, the syl of the second syllable is deleted.
If linked syllables are unlinked, the second syllable has a new syl created with a default bounding box taken from the children of the syllable.
=> Add and remove syl tags when associating/deassociating syllables

src/SquareEdit/SelectOptions.js
=> Remove context menu after actions.

src/DivaView.js, src/NeonView.js, src/SingleView/SingleView.js, src/SquareEdit/Grouping.js, src/TextView.js, src/style.css, src/utils/Color.js, src/utils/DragHandler.js, src/utils/Resize.js, src/utils/SelectTools.js
- resolves #462: changes to what gets highlighted and selected when clicking on or mousing over things, and added highlighting of text when selecting it's syllable
- resolves #468: change to burger menu view at a slightly smaller width
- resolves #472: change changePage() and updateForCurrentPage() functions so that they take an optional parameter as to whether to delay loading the verovio render. In the case of loading the page for the first time it should delay (on diva view specifically), but when doing editor actions it should not. This fixes #466 and fixes #469 
- resolves #467 by changing the aesthetic and functionality of resizing
- resolves #473 
- resolves #474
=> resolve UI and boundingbox/text highlighting issues

.travis.yml, test/NeonCore.test.js
resolves #446 and resolves #463 by merging changes from DDMAL/Verovio#31
and wrote tests to check behaviour implemented 
also added 'yarn upgrade verovio-dev' to the travis file, since it not being there was causing the travis builds to fail
=> new verovio builds for clef re-association

.travis.yml, src/DisplayPanel/DisplayControls.js, src/SquareEdit/Controls.js, src/TextEditMode.js, src/utils/Color.js, src/utils/EditControls.js
=> optional highlighting tied to selection mode

src/utils/template/Template.js, src/utils/template/template.html, webpack.config.js, webpack.pages-config.js
Add version info to Neon for development mode. This will have to be manually changed on releases. Resolves #485.
=> Add version information to Neon

pages/static/editor.html, src/style.css, views/editor.pug
=> Make horizontal diva scrollbar visible

src/NeonCore.js, test/NeonCore.test.js, yarn.lock
=> Handle Verovio info as JSON object

test/DivaBrowser.test.js, test/SinglePageBrowser.test.js
Check if node.js platform value is "darwin" (open source parts of Mac OS). Resolve #499.
=> Run Safari browser tests on Mac OS only

src/utils/Select.js
=> Unset handler before resetting it.

src/utils/SelectTools.js
This should resolve #506 and doesn't seem to break anything.
=> Do not overwrite select highlight of staves

src/SquareEdit/Controls.js
=> Ensure insert click listeners are removed when using hotkeys.

src/TextEditMode.js
=> Get ID of syl in TextEditMode a better way.

src/DivaView.js
Otherwise the layout will not be correct in diva.js.
=> Reload the SVG when window resizes

src/SquareEdit/InsertHandler.js, test/resources/test.mei, test/resources/testSb.mei, test/resources/testStaff.mei
resolves #521 and #523 and added clef to staff def in some test files
new vrv build from https://github.com/DDMAL/verovio/commit/17f99472cefa1c72b2245da14dbbbb1a5c777965 and https://github.com/DDMAL/verovio/commit/f70759294a676e9982abfc1407ce8661ffe2cbf9
=> fixes to test files, clef inserting ui, pitched element insertion in verovio

package.json, src/Types.ts, test/ConvertMei.test.ts, test/DirectoryTraversal.test.ts, test/DivaBrowser.test.ts, test/NeonCore.test.ts, test/Notification.test.ts, test/SinglePageBrowser.test.ts, test/SubstituteValidation.js, test/SubstituteValidation.ts, test/VerovioWrapper.ts, test/Zoom.test.ts, tsconfig.json, yarn.lock
Convert all tests to Typescript, installing dependencies and making minor changes to other files as necessary.
=> Convert Tests to Typescript

src/utils/EditContents.js, src/utils/EditControls.js
Basically commit 64cc25b but in JavaScript instead of TS.
=> Set up File dropdown using HTMLElements not raw HTML

src/utils/Resize.ts, src/utils/SelectTools.ts, test/NeonCore.test.ts
fix resize so that it caps skew properly, make it so that staff merging button shows up for any number of staves (at any distance), update neoncore test for capped skew, and new verovio builds for skewed merge and split.
see https://github.com/DDMAL/verovio/pull/34, #534, #543
=> staff merge and split with skew

pages/static/index.css, pages/static/index.html
Actually label what things do. Include links to DDMAL and SIMSSA.
Mention Neon. Resolve #546.
=> Improve GH pages home page.

pages/static/index.css, pages/static/index.html
This applies the same changes as #549 but to the master branch as well since we build GH pages from there.
=> Improve GitHub Pages home page

src/SquareEdit/InsertHandler.ts, test/SinglePageBrowser.test.ts, yarn.lock
If a previous option was not selected, null would be dereferenced. Now
we check for null.
Resolve #586.
=> Fix issue with insert hotkeys

src/workers/VerovioWorker.js, test/DivaBrowser.test.ts, test/NeonCore.test.ts, test/VerovioWrapper.ts, yarn.lock
This uses the version of Verovio from DDMAL/verovio@2aebf75
=> Update Verovio with tweaks to NeonCore.

src/SquareEdit/Contents.ts, src/SquareEdit/SelectOptions.ts, src/utils/Color.ts, src/utils/Resize.ts, src/utils/Select.ts, src/utils/SelectTools.ts, src/workers/VerovioWorker.js
Since `@skew` isn't going to happen, implement and use TEI's `@rotate`,
which is more likely to happen. See DDMAL/verovio@30d716dde41fccc7ca5290bdd39e623cf0bb8421 for more.
=> Switch skew to rotate

src/NeonCore.ts, test/NeonCore.test.ts
After changes to our Verovio fork insert was slightly off. These are tweaks to help correct that.
=> Tweak insert and drag slightly

src/NeonCore.ts
Resolve #620. This should also be merged into master.
=> Ensure all annotations are updated locally

src/utils/Color.ts
This also fixes some TypeErrors that came up previously but didn't cause
major issues.
=> Tweak highlight stroke to size of image

package.json, src/utils/ConvertMei.ts, yarn.lock
Pretty print the MEI since the javascript XMLSerializer doesn't do this. Resolve #631.
=> Pretty print MEI

src/InfoModule.ts, src/SquareEdit/Contents.ts, src/SquareEdit/InsertHandler.ts, src/SquareEdit/SelectOptions.ts, src/utils/Color.ts, src/utils/SelectTools.ts
Invalid is due to miss-spelling of divLine into divline
=> divline invalid fix done

src/InfoModule.ts
solved the invalid status issue due to ungroup neumes
=> ungroup invalid status fix done

src/workers/Worker.js
=> fix syllable no option issue

src/DisplayPanel/DisplayControls.ts, src/utils/SelectTools.ts
=> fix multiple syllable option

src/SquareEdit/Contents.ts
issue #661 : change accidental shape menu
=> change accid to accidental

src/SquareEdit/Contents.ts, src/SquareEdit/Grouping.ts, src/SquareEdit/SelectOptions.ts, src/utils/SelectTools.ts
issue #762 , add insert accid/divisio to syllable feature, simplify grouping when accid/divLine in between syllables
=> add insert accid/divisio to syllable feature

src/utils/ConvertMei.ts
=> fix mei encoding for toggle-linked syllable and  toggle-link-caused no syllable option issue

src/utils/ConvertMei.ts
=> add empty neume check to ConvertMei

src/SquareEdit/Grouping.ts
Fix Neon issue #777 and issue #641
=> move isLigature check to verovio

src/utils/ConvertMei.ts
remove the automatic check for #727 debugging
=> remove neume no nc check

src/utils/ConvertMei.ts
fix Neon issue #794 
The issue is caused by no syllables found after a toggle-linked syllable. The fix is to convert the automatic correction to notification of an error, i.e. 1) no syllable found after a toggle-linked syllable, 2) the `@xml:id` does not match, 3) no `@precedes `or `@follows` found in the corresponding syllable.
=> convert toggle-linked correction to notification

src/utils/ConvertMei.ts
minor changes for Rodan build failure
=> minor changes

src/SquareEdit/InsertHandler.ts, src/utils/Select.ts
Press enter key on a selected bounding box to edit its text; related to #665 .
Demo:
https://user-images.githubusercontent.com/40512164/167931249-fe15cea9-f62c-4de0-8b3c-3fefe0147831.mov
=> Add enter key shortcut functionality

src/SquareEdit/InsertHandler.ts, src/utils/Select.ts
=> Revert "Add enter key shortcut functionality"

src/DisplayPanel/DisplayControls.ts, src/Types.ts, src/utils/Color.ts, src/utils/ConvertMei.ts, src/utils/Select.ts
Key shortcut as mentioned in issue #665 .
Demo:
https://user-images.githubusercontent.com/40512164/167684349-7dbb39d4-e889-49f8-8ea1-86005f20b4b1.mov
=> Add "switch highlight modes" key shortcuts.

src/utils/SelectTools.ts
#797 
fix toggle ligature vs group nc components button. takes into account ascending and descending nc's.
=> Toggle ligature fix

src/SquareEdit/InsertHandler.ts, src/utils/Select.ts
As seen in #810 .
Press enter key on a selected bounding box to edit its text; related to #665 .
Demo:
https://user-images.githubusercontent.com/40512164/167931249-fe15cea9-f62c-4de0-8b3c-3fefe0147831.mov
=> Add enter key shortcut functionality.

assets/template.html, src/NeonView.ts, src/utils/template/Template.ts
Added "Remove Empty Neumes" and "Remove Empty Syllables" buttons to the main navbar. Added event handlers for those buttons as well.
=> Added "remove empty neumes" and "remove empty syllables" buttons

src/SquareEdit/Grouping.ts, src/SquareEdit/SelectOptions.ts, src/utils/SelectTools.ts
Adds one of requested features from request #665
=> Implemented grouping/ungrouping hotkeys

src/DisplayPanel/DisplayControls.ts, src/DisplayPanel/DisplayPanel.ts, src/Interfaces.ts, src/SingleView/SingleView.ts, src/SingleView/Zoom.ts, test/Zoom.test.ts
Fixes #818 . Solves zooming issue in #683 .
+ Change zoom slider to use "lazy zoom", which should get rid of the lag
+ Fix Zoom.ts variable names, for developer sanity.
+ Make sliders look prettier.
+ Reformat DisplayPanel.ts's HTML strings.
+ Fix opacity sliders as well.
Sliders are visually and functionally disabled until the document is loaded:
https://user-images.githubusercontent.com/40512164/168622221-faf4e36d-8e25-471e-8631-6b055cfcc3b7.mov
"Lazy zoom":
https://user-images.githubusercontent.com/40512164/168622332-310fc483-c0e7-4360-8c8d-89dd087e1496.mov
=> Fix zoom slider 

assets/template.html, src/Interfaces.ts, src/TextEditMode.ts, src/TextView.ts, src/utils/ModalWindow.ts, src/utils/Select.ts
♻️ Remove console log and extract variable.
🐛 Fix empty bbox selected.
🐛 Fix keyboard shortcuts not working after hiding modal (w/ David).
=> 🐛 Fix selection of syllable after edit modal.

src/SquareEdit/Contents.ts, src/SquareEdit/SelectOptions.ts, src/Types.ts, src/utils/SelectTools.ts
As requested in issue #841 and #762, added a button that can move divLine and accid out of a syllable if they are inside syllable. Will add this function to clef soon.
=> add moveOuttaSyllable button for layer elements

src/SquareEdit/Contents.ts, src/SquareEdit/Controls.ts, src/SquareEdit/Grouping.ts, src/SquareEdit/SelectOptions.ts, src/TextEditMode.ts, src/TextView.ts, src/Types.ts, src/utils/Color.ts, src/utils/SelectTools.ts, test/SinglePageBrowser.test.ts
=> add changeStaffListen when select multiple syllable

src/SquareEdit/SingleEditMode.ts
=> 🐛 Fixed bug that was causing Neon to start in Insert mode instead of Edit mode

src/SquareEdit/Controls.ts
Yes, it's a one-line fix lol.
This took a while.
=> 🐛 Fix for issue that was causing hotkeys for selected nth insert option to not work

src/DisplayPanel/DisplayControls.ts, src/SquareEdit/Controls.ts, src/SquareEdit/DivaEditMode.ts
Mode no longer changes in response to user click on panel headings.
=> 🐛 Fixed issue that was causing misleading visual cues regarding which mode user is in (Edit vs Insert)

src/TextView.ts
=> 🐛 Fix highlight of bounding box when hovering over syllable texts

src/SquareEdit/InsertHandler.ts, src/utils/Coordinates.ts, src/utils/DragHandler.ts, src/utils/Select.ts, src/utils/SelectTools.ts
Fixes #700 , at least for single glyphs / staves.
Now a notification will show up if you have placed a glyph out of bounds.
https://user-images.githubusercontent.com/40512164/177211574-3e2e46cf-d6f5-484f-8d13-aa01cc2a8b2e.mov
=> 🐛 Disable out-of-bounds glyph placement

src/utils/Coordinates.ts, src/utils/Select.ts
Fixes #927 . Made a mistake in calculation from PR #911 .
=> 🐛 Fix inside-drag-selection calculation

src/SquareEdit/InsertHandler.ts
=> 🐛 Add staff out-of-bounds check

src/utils/Coordinates.ts, src/utils/DragHandler.ts
Fix #700 false positive OOB calculation for syl bounding boxes.
=> 🚑 Fix OOB calculation for syl bounding boxes

src/utils/Resize.ts
=> 🐛 Fix highlight of staves after resize or rotate

.gitignore, deployment/server/editor.html, package.json, yarn.lock
Each commit corresponds to one point:
- Fix https issue with d3.js
- Add /deployment/public to .gitignore
- Turn off HTML quirks mode 
- Set diva.js to a specific release
=> Fix configuration scripts

.eslintrc.json, assets/style.css, assets/template.html, cypress/e2e/errorlog.cy.ts, src/NeonView.ts, src/SquareEdit/Contents.ts, src/utils/ErrorLog.ts, src/utils/Notification.ts, src/utils/template/Template.ts
Fixes https://github.com/DDMAL/Neon/issues/950 .
=> 🐛 Rename notification log --> error log; fix error log filtering

src/InfoModule.ts, src/NeonView.ts, src/Types.ts, src/utils/SelectTools.ts
+ Refactor InfoModule.ts and SelectTools.ts with correct typings for `Attributes`
https://user-images.githubusercontent.com/40512164/185269458-af1ac876-b386-4197-9e52-393b3e26cbac.mov
=> ✨️ Display octave information for clefs

src/DisplayPanel/DisplayControls.ts, src/utils/SelectTools.ts
=> 🐛 fix syllable select in highlight by neume mode

src/SquareEdit/Grouping.ts, src/utils/SelectTools.ts
=> 🐛 fix merging with clef in between & error message when selecting layer elements in neume mode
